@hostname = http://localhost:9999/auth
@id = "61f028f9f2120edbc5fa8a21"

post {{hostname}}/registerUser
Content-Type: application/json

{
    "user" : {
        "userName": "harshil123",
        "firstName": "Dicit",
        "lastName": "Dangi",
        "mobile": "9723445038",
        "email": "homionapp@gmail.com",
        "password": "Homion@123"
    }
}
###
post {{hostname}}/login
Content-Type: application/json

{
    "email": "homionapp@gmail.com",
    "password": "Homion@123",
    "type": "USER"
}
###

###
post {{hostname}}/forgotPassword
Content-Type: application/json

{
    "email": "homionapp@gmail.com",
    "type": "USER"
}
###

###
post {{hostname}}/resetPassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvbWlvbmFwcEBnbWFpbC5jb20iLCJ0eXBlIjoiVVNFUiIsImlhdCI6MTY0MzIyMDI3MiwiZXhwIjoxNjQzMjIwMjczfQ.GhxnvcJtlnqV63Nnt7aiQ3IfhfqYVO6f00j7KoOdAOk
Content-Type: application/json

{
    "password": "Homion@1234"
}
###

GET {{hostname}}/getUsers
###

DELETE  {{hostname}}/dltUsers
###