@hostname = http://localhost:9999/auth
@id = "61f028f9f2120edbc5fa8a21"

post {{hostname}}/registerUser
Content-Type: application/json

{
    "user" : {
        "userName": "dixit.99",
        "firstName": "Dixit",
        "lastName": "Dodiya",
        "mobile": "9723445038",
        "email": "homionapp@gmail.com",
        "password": "Homion@123"
        
    }
}
###
post {{hostname}}/login
Content-Type: application/json

{
    "email": "homionapp@gmail.com",
    "password": "Homion@123",
    "type": "CHEF"
}
###

###
post {{hostname}}/forgotPassword
Content-Type: application/json

{
    "email": "homionapp@gmail.com",
    "type": "USER"
}
###

###
post {{hostname}}/resetPassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvbWlvbmFwcEBnbWFpbC5jb20iLCJ0eXBlIjoiVVNFUiIsImlhdCI6MTY0MzMwODkyMSwiZXhwIjoxNjQzMzE2MTIxfQ.Qq-eUjOfJjPSE8yO36KPkkycy5ZVLIYSbot8B3CrVME
Content-Type: application/json

{
    "password": "omion@1234"
}
###

###
post {{hostname}}/registerChef
Content-Type: application/json

{
    "chef" : {
        "userName": "hardik123",
        "firstName": "Amareliye",
        "lastName": "Dodiya",
        "mobile": "9723445038",
        "email": "homionapp@gmail.com",
        "password": "Homion@123",
        "panNumber": "DLH4433R"
    }
}

###
GET {{hostname}}/getUsers
###

DELETE  {{hostname}}/dltUsers
###

GET {{hostname}}/getChefs
###

DELETE  {{hostname}}/dltChefs
###