@hostname = http://localhost:9999/chef
@id = "61f028f9f2120edbc5fa8a21"


post {{hostname}}/addProduct
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjk1OTA4MTdlNzhjZThmNDE3MzM4MCIsImVtYWlsIjoiaG9taW9uYXBwQGdtYWlsLmNvbSIsInR5cGUiOiJDSEVGIiwiaWF0IjoxNjQ0NDIyMTA1LCJleHAiOjE2NDUwMjY5MDV9.aBivnE2m8yanPETjtagvuIzOwDBcQwKdUJXZPtFZ6tg
Content-Type: application/json

{
    "product" : {
        "name": "Fafda",
        "price": 100,
        "unitValue": 100,
        "unitType": "gm",
        "prepTime": 30,
        "isSpeciality": true,
        "isOpenForHome": false,
        "isJainAvailable": false        
    }
}
###

post {{hostname}}/addCategory
Content-Type: application/json

{
    "name" : "Punjabi"
}
###

get {{hostname}}/getCategories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjk1OTA4MTdlNzhjZThmNDE3MzM4MCIsImVtYWlsIjoiaG9taW9uYXBwQGdtYWlsLmNvbSIsInR5cGUiOiJDSEVGIiwiaWF0IjoxNjQ0NDIyMTA1LCJleHAiOjE2NDUwMjY5MDV9.aBivnE2m8yanPETjtagvuIzOwDBcQwKdUJXZPtFZ6tg
Content-Type: application/json
###

post {{hostname}}/addSubCategory
Content-Type: application/json

{
    "name" : "Breakfast"
}
###

get {{hostname}}/getSubCategories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjk1OTA4MTdlNzhjZThmNDE3MzM4MCIsImVtYWlsIjoiaG9taW9uYXBwQGdtYWlsLmNvbSIsInR5cGUiOiJDSEVGIiwiaWF0IjoxNjQ0NDIyMTA1LCJleHAiOjE2NDUwMjY5MDV9.aBivnE2m8yanPETjtagvuIzOwDBcQwKdUJXZPtFZ6tg
Content-Type: application/json
###